//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FutureConcepts.Mobile.Server.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=C:\\testdb\\ICCMappingDatabase.mdf;Integr" +
            "ated Security=True;Connect Timeout=30;User Instance=True")]
        public string ICCMappingDatabaseConnectionString {
            get {
                return ((string)(this["ICCMappingDatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=\"C:\\Program Files\\Microsoft SQL Server\\" +
            "MSSQL10.SQLEXPRESS\\MSSQL\\DATA\\AntaresXWeb.MDF.mdf\";Integrated Security=True;Conn" +
            "ect Timeout=30;User Instance=True")]
        public string AntaresXWeb_MDFConnectionString {
            get {
                return ((string)(this["AntaresXWeb_MDFConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=\"C:\\Program Files\\Microsoft SQL Server\\" +
            "MSSQL10.SQLEXPRESS\\MSSQL\\DATA\\ICCMAPPINGDATABASE.MDF.mdf\";Integrated Security=Tr" +
            "ue;Connect Timeout=30;User Instance=True")]
        public string ICCMAPPINGDATABASE_MDFConnectionString {
            get {
                return ((string)(this["ICCMAPPINGDATABASE_MDFConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=\"C:\\Program Files\\Microsoft SQL Server\\" +
            "MSSQL10.SQLEXPRESS\\MSSQL\\DATA\\AntaresXWeb.mdf\";Integrated Security=True;Connect " +
            "Timeout=30;User Instance=True")]
        public string AntaresXWebConnectionString {
            get {
                return ((string)(this["AntaresXWebConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=C:\\testdb\\AntaresXWeb.MDF.mdf;Integrate" +
            "d Security=True;Connect Timeout=30;User Instance=True")]
        public string AntaresXWeb_MDFConnectionString1 {
            get {
                return ((string)(this["AntaresXWeb_MDFConnectionString1"]));
            }
        }
    }
}
